# Generic labels
- name: bug
  description: Something isn't working
  color: d73a4a
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: enhancement
  description: New feature or request
  color: a2eeef
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: wontfix
  description: This will not be worked on
  color: ffffff
- name: blocked
  description: This issue is blocked by some other work
  color: e0af74
- name: critical
  description: This issue needs critical attention
  color: B60205
- name: infra
  description: Infra, devops, CI and related tasks
  color: 277196
- name: milestone
  description: Tracks a subteam milestone
  color: 1CC0B0
- name: epic
  description: Tracks a yearly team epic (only for codex-storage/codex-pm repo)
  color: 07544B
- name: test
  description: Issue related to the test suite with no expected consequence to production code
  color: 277196
- name: release-notes
  description: Issue/PR needs to be evaluated for inclusion in release notes highlights or upgrade instructions
  color: fb3c99
- name: dependencies
  description: Pull requests that update a dependency file or issues that track it
  color: 0366d6

# Everything below this comment requires updating for Codex

## Epics belonging to [Milestone] Codex Testnet Phase 0 (Codex - PoC 3 Longsword)
- name: "E:1.1 Improve Client Stability"
  description: See https://github.com/waku-org/pm/issues/62 for details
  color: 20A609
- name: "E:1.2: Block Discovery and Retrieval"
  description: See https://github.com/waku-org/pm/issues/65 for details
  color: 5319e7
- name: "E:1.3: Wiring the Proving System"
  description: See https://github.com/waku-org/pm/issues/66 for details
  color: 8A5EE0
- name: "E:1.4: Multi-threading"
  description: See https://github.com/waku-org/pm/issues/67 for details
  color: 244B5B
- name: "E:1.5: Refine Proving System"
  description: See https://github.com/waku-org/pm/issues/68 for details
  color: 195A49
- name: "E:1.6: Implement Poseidon2"
  description: See https://github.com/waku-org/pm/issues/49 for details
  color: e99695
- name: "E:1.7: Merkelizing Block Data"
  description: See https://github.com/waku-org/pm/issues/63 for details
  color: 92A880
- name: "E:1.8: Request Proving Scheme Marketplace Integration"
  description: See https://github.com/waku-org/pm/issues/64 for details
  color: 37BEA9
- name: "E:1.9: Update Marketplace to New Design"
  description: See https://github.com/waku-org/pm/issues/69 for details
  color: B342EA
- name: "E:1.10: End-to-end Testing"
  description: See https://github.com/waku-org/pm/issues/70 for details
  color: DF42D5
- name: "E:1.11: Marketplace Walkthrough and Cleanup"
  description: See https://github.com/waku-org/pm/issues/87 for details
  color: e99695

## Orphaned Epics
- name: "E:Fuzzing"
  description: See https://github.com/waku-org/pm/issues/35 for details
  color: 2B4DAF
- name: "E:Auditing Tools"
  description: See https://github.com/waku-org/pm/issues/90 for details
  color: 088DF8
- name: "E:Repair"
  description: See https://github.com/waku-org/pm/issues/96 for details
  color: 0e8a16
- name: "E:Slot Reservations"
  description: See https://github.com/waku-org/pm/issues/95 for details
  color: 95D888
- name: "E:Expanding Window"
  description: see https://github.com/waku-org/pm/issues/98 for details
  color: 54D412
- name: "E:Bandwidth Payments"
  description: see https://github.com/waku-org/pm/issues/98 for details
  color: E6E6FA
- name: "E:Testnet Setup"
  description: see https://github.com/waku-org/pm/issues/98 for details
  color: 00FFCC
- name: "E:Distributed Client Testing"
  description: see https://github.com/waku-org/pm/issues/98 for details
  color: C33919
- name: "E:Infra Planning"
  description: see https://github.com/waku-org/pm/issues/98 for details
  color: 27D128
- name: "E:Bare Metal Testing"
  description: see https://github.com/waku-org/pm/issues/98 for details
  color: F2CE72
  